# Generated by Django 3.2.7 on 2021-11-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default=12, max_length=10),
            preserve_default=False,
        ),
    ]
