# Generated by Django 3.2.7 on 2021-11-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('departure_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('cityfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='travel.airport')),
                ('cityto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='travel.airport')),
            ],
        ),
    ]
