# Generated by Django 3.2.7 on 2021-11-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_book_flightpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fp', to='travel.flightpayment'),
        ),
    ]
