# Generated by Django 3.2.7 on 2021-12-03 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_book_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertcityfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertf', to='travel.airport')),
                ('alertcityto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertt', to='travel.airport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
